name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          ## configure
          config_display: large
          template: classic
          config_timezone: Asia/Seoul
          
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, perl
          plugin_languages_limit: 5
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons



